### ISSUE TITLE
Inputting many revisions and outputting CNF

### ISSUE THREAD

**Issue by plward11** [aetilley/pcfg_scorer#1]
@aetilley I notice that there is a utility for getting revisions from Wikipedia in `data/get_sents.py`. Is there functionality in `pcfg.py` that can easily process sentences from the revision data dump and train a new PCFG from that? I've noticed the `train_from_file` function, but that expects files in the CNF_COUNTS or UNIV_PCFG formats.

Also, is there a way to output the current PCFG in the UNIV_PCFG format?

I'd be happy to help, if you think these features are appropriate.

**Comment by aetilley** [comment]
Hi Patrick

In short, no there's currently not a quick way to take a WP dump as input and output a corresponding PCFG object (or, equivalently, output a corresponding UNIV_PCFG file).  I have just added a short description of the bottleneck in the abstract at the bottom of the README.

But you do point out some features that should probably be added, and I'd be happy to talk more.  Let me try to get back to you in the next couple days.

best,
Arthur

**Comment by plward11** [comment]
Hi Arthur,

Really appreciate the clear explanation and the description in the README.

Looking forward to talking more with you in the next couple of days.

Best,
Patrick

**Comment by aetilley** [comment]
Hi Patrick,

Closing this.  UNIV_COUNTS format functionality now provided.  Also self.print_pcfg(<pathname>) now implemented.

cnf_counts file format now officially unsupported.

best,
Arthur

**Comment by ManhND27** [comment]
can you show me the results ? please
